### ISSUE TITLE
`npm run release` stopped working

### ISSUE THREAD

**Issue by jvanoostveen** [AFASSoftware/typescript-assistant#25]
As I can't pinpoint on the why, I defer it to an issue, maybe I can reproduce the issue on other machines which can switch Node versions a lot easier instead of uninstalling and installing.
Running `npm version minor` does seem te work...
Already tried setting different options to the `spawn` command in the taskrunner.

Script output:
```
npm run release

> typescript-assistant@0.31.10 release C:\Users\jvo\Projects\typescript-assistant
> ts-node --transpileOnly src/index.ts release

git:
  running command git status --porcelain
  running command git rev-parse --abbrev-ref HEAD
? What type of bump would you like to do? minor
npm:
  running command npm.cmd version minor
  v0.32.0
! npm ERR! code 1
! npm ERR! Command failed: git -c core.longpaths=true commit -m 0.32.0
! npm ERR! error: cannot spawn .git/hooks/pre-commit: No such file or directory
```

The log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'version',
1 verbose cli   'minor' ]
2 info using npm@6.1.0
3 info using node@v10.3.0
4 info git [ 'status', '--porcelain' ]
5 info lifecycle typescript-assistant@0.32.0~preversion: typescript-assistant@0.32.0
6 verbose version.write data { name: 'typescript-assistant',
6 verbose version.write   version: '0.32.0',
6 verbose version.write   description:
6 verbose version.write    'Combines and integrates professional Typescript tools into your project',
6 verbose version.write   main: 'dist/index.js',
6 verbose version.write   bin: { tsa: './dist/index.js' },
6 verbose version.write   scripts:
6 verbose version.write    { prepublishOnly: 'tsc -p ./src/tsconfig.json',
6 verbose version.write      assist: 'ts-node --transpileOnly src/index.ts',
6 verbose version.write      release: 'ts-node --transpileOnly src/index.ts release',
6 verbose version.write      fix: 'ts-node --transpileOnly src/index fix',
6 verbose version.write      clean: 'ts-node --transpileOnly src/index clean',
6 verbose version.write      'coverage-show': 'opn build/coverage/index.html',
6 verbose version.write      tslint:
6 verbose version.write       'tslint --project ./src/tsconfig.json ./src/**/*.ts && tslint --project ./tsconfig.json ./test/**/*.ts',
6 verbose version.write      ci: 'ts-node --transpileOnly src/index ci',
6 verbose version.write      postcheckout: 'ts-node --transpileOnly src/index post-checkout || exit 0',
6 verbose version.write      postmerge: 'ts-node --transpileOnly src/index post-merge || exit 0',
6 verbose version.write      precommit: 'ts-node --transpileOnly src/index pre-commit',
6 verbose version.write      prepush: 'ts-node --transpileOnly src/index pre-push' },
6 verbose version.write   author: 'johan@johangorter.com',
6 verbose version.write   license: 'MIT',
6 verbose version.write   repository:
6 verbose version.write    { type: 'git',
6 verbose version.write      url: 'https://github.com/AFASSoftware/typescript-assistant' },
6 verbose version.write   nyc:
6 verbose version.write    { include: [ 'src/**/*.ts' ],
6 verbose version.write      extension: [ '.ts' ],
6 verbose version.write      reporter: [ 'json', 'html', 'text-summary' ],
6 verbose version.write      cache: true,
6 verbose version.write      'temp-directory': './build/nyc/cache',
6 verbose version.write      all: true,
6 verbose version.write      'check-coverage': false,
6 verbose version.write      'report-dir': './build/coverage',
6 verbose version.write      'es-module': false,
6 verbose version.write      lines: 1,
6 verbose version.write      statements: 0.1,
6 verbose version.write      functions: 0.1,
6 verbose version.write      branches: 0,
6 verbose version.write      watermarks:
6 verbose version.write       { lines: [Array],
6 verbose version.write         functions: [Array],
6 verbose version.write         branches: [Array],
6 verbose version.write         statements: [Array] } },
6 verbose version.write   dependencies:
6 verbose version.write    { '@types/chai': '4.1.3',
6 verbose version.write      '@types/mocha': '5.2.0',
6 verbose version.write      '@types/node': '10.1.2',
6 verbose version.write      async: '2.6.1',
6 verbose version.write      chai: '4.1.2',
6 verbose version.write      chokidar: '2.0.3',
6 verbose version.write      glob: '7.1.2',
6 verbose version.write      handlebars: '4.0.11',
6 verbose version.write      husky: '0.14.3',
6 verbose version.write      inquirer: '5.2.0',
6 verbose version.write      mocha: '5.2.0',
6 verbose version.write      nyc: '11.8.0',
6 verbose version.write      'opn-cli': '3.1.0',
6 verbose version.write      semver: '5.5.0',
6 verbose version.write      'source-map-support': '0.5.6',
6 verbose version.write      'tree-kill': '1.2.0',
6 verbose version.write      'ts-node': '6.0.5',
6 verbose version.write      tslib: '1.9.1',
6 verbose version.write      tslint: '5.10.0',
6 verbose version.write      'tslint-microsoft-contrib': '5.0.3',
6 verbose version.write      'tslint-sonarts': '1.6.0',
6 verbose version.write      tsutils: '2.27.1',
6 verbose version.write      typescript: '2.8.3',
6 verbose version.write      'typescript-formatter': '7.2.0',
6 verbose version.write      ws: '5.2.0',
6 verbose version.write      yargs: '11.0.0' },
6 verbose version.write   devDependencies:
6 verbose version.write    { '@types/async': '2.0.49',
6 verbose version.write      '@types/chokidar': '1.7.5',
6 verbose version.write      '@types/glob': '5.0.35',
6 verbose version.write      '@types/handlebars': '4.0.37',
6 verbose version.write      '@types/inquirer': '0.0.36',
6 verbose version.write      '@types/semver': '5.5.0',
6 verbose version.write      '@types/sinon': '5.0.0',
6 verbose version.write      '@types/ws': '5.1.1',
6 verbose version.write      '@types/yargs': '11.0.0',
6 verbose version.write      sinon: '5.0.10' } } to package.json
7 info lifecycle typescript-assistant@0.32.0~version: typescript-assistant@0.32.0
8 info git [ 'add',
8 info git   'C:\\Users\\user\\Projects\\typescript-assistant\\package.json' ]
9 info git [ 'commit', '-m', '0.32.0' ]
10 verbose stack Error: Command failed: git -c core.longpaths=true commit -m 0.32.0
10 verbose stack error: cannot spawn .git/hooks/pre-commit: No such file or directory
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:291:12)
10 verbose stack     at ChildProcess.emit (events.js:182:13)
10 verbose stack     at maybeClose (internal/child_process.js:961:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
11 verbose cwd C:\Users\user\Projects\typescript-assistant
12 verbose Windows_NT 10.0.16299
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "version" "minor"
14 verbose node v10.3.0
15 verbose npm  v6.1.0
16 error code 1
17 error Command failed: git -c core.longpaths=true commit -m 0.32.0
17 error error: cannot spawn .git/hooks/pre-commit: No such file or directory
18 verbose exit [ 1, true ]
```

**Comment by jvanoostveen** [comment]
Haven't had the issue for a really really long time, closing it.
